support new confluencebuilder
The `confluencebuilder` has made some changes in its v1.4 release which
breaks the integration in this extension. Changes to the image node
processing now requires a depart hook which will result in the following
error:

    NotImplementedError: <class 'sphinxcontrib.confluencebuilder.translator.storage.ConfluenceStorageFormatTranslator'> departing unknown node type: plantuml

Explicitly register depart hook to allow the depart chain to complete.

The `confluencebuilder` extension now provides automatic handling of
image (asset) management if dynamically creating during the translation
phase. Therefore, simplifying the implementation by dropping the need to
forcefully process the asset manager.

Signed-off-by: James Knight <james.d.knight@live.com>